<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Contact Us Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'info@cc-catering.com',
		'to' => 'info@cc-catering.com'
	),
	'recaptcha2' => array(
		'private_key' => 'null'
	),
	'fields' => array(
		'custom_U9770' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Full Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Full Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U9780' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Message',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Message\' is required.'
			)
		),
		'custom_U9953' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Home Address',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U9965' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'City',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U9977' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'State',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U9989' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Zip code',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U10013' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Phone\' is required.'
			)
		),
		'custom_U10025' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Date of Affair (if known)',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U10037' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Approximate Number of Guests (if known)',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U10049' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Occasion',
			'required' => false,
			'errors' => array(
			)
		),
		'g-recaptcha-response' => array(
			'order' => 12,
			'type' => 'recaptcha2',
			'label' => 'Image Verification',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Image Verification\' is required.',
				'format' => 'Incorrect reCAPTCHA 2.0 value.'
			)
		)
	)
);

process_form($form);
?>
